[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 200
remappings = [
  "ds-test/=lib/ds-test/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
verbosity = 3

[ci]
fuzz_runs = 100_000
verbosity = 5
